// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Alumni.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Alumni.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlumniDbContext))]
    [Migration("20260908195746_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alumni")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Alumni.Alumnus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bio");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentEmployer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("current_employer");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.Property<bool>("HideContactDetails")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_contact_details");

                    b.Property<bool>("HideCurrentEmployer")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_current_employer");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("profile_visibility");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<Guid>("StudentIdRef")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id_ref");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_alumni_department_id");

                    b.HasIndex("GraduationYear")
                        .HasDatabaseName("ix_alumni_graduation_year");

                    b.HasIndex("ProfileVisibility")
                        .HasDatabaseName("ix_alumni_profile_visibility");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_alumni_program_id");

                    b.HasIndex("StudentIdRef")
                        .IsUnique()
                        .HasDatabaseName("ux_alumni_student_id_ref");

                    b.ToTable("alumni", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.AlumniEvents.AlumniEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<Guid?>("ContentEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_alumni_events_chapter_id");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_alumni_events_event_date");

                    b.ToTable("alumni_events", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.AlumniEvents.AlumniEventRsvp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlumnusId")
                        .HasColumnType("uuid")
                        .HasColumnName("alumnus_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<DateTimeOffset>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "AlumnusId")
                        .IsUnique()
                        .HasDatabaseName("ux_alumni_event_rsvps_event_alumnus");

                    b.ToTable("alumni_event_rsvps", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Chapters.AlumniChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("region");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("alumni_chapters", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Donations.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlumnusId")
                        .HasColumnType("uuid")
                        .HasColumnName("alumnus_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<DateTimeOffset?>("NextChargeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_charge_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RecurrenceInterval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence_interval");

                    b.Property<string>("RecurrenceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence_status");

                    b.Property<Guid?>("SeriesRootDonationId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_root_donation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AlumnusId")
                        .HasDatabaseName("ix_donations_alumnus_id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_donations_campaign_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_donations_invoice_id");

                    b.HasIndex("SeriesRootDonationId")
                        .HasDatabaseName("ix_donations_series_root_donation_id");

                    b.HasIndex("RecurrenceStatus", "NextChargeAt")
                        .HasDatabaseName("ix_donations_recurrence_status_next_charge_at");

                    b.ToTable("donations", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Donations.DonationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ClosedEarly")
                        .HasColumnType("boolean")
                        .HasColumnName("closed_early");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<decimal>("GoalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("goal_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StartsAt", "EndsAt")
                        .HasDatabaseName("ix_donation_campaigns_window");

                    b.ToTable("donation_campaigns", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Jobs.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApplicantIsAlumnus")
                        .HasColumnType("boolean")
                        .HasColumnName("applicant_is_alumnus");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_user_id");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ResumeArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_artifact_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId")
                        .HasDatabaseName("ix_job_applications_applicant_user_id");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_job_applications_job_posting_id");

                    b.ToTable("job_applications", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Jobs.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company");

                    b.Property<string>("ContactMethod")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact_method");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("moderation_reason");

                    b.Property<Guid?>("PosterAlumnusId")
                        .HasColumnType("uuid")
                        .HasColumnName("poster_alumnus_id");

                    b.Property<bool>("PosterIsAlumnus")
                        .HasColumnType("boolean")
                        .HasColumnName("poster_is_alumnus");

                    b.Property<Guid>("PosterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("poster_user_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PosterUserId")
                        .HasDatabaseName("ix_job_postings_poster_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_postings_status");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_job_postings_status_expires_at");

                    b.ToTable("job_postings", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Mentorship.MentorshipMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("EndedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ended_reason");

                    b.Property<DateTimeOffset?>("MenteeAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mentee_accepted_at");

                    b.Property<Guid>("MenteeStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentee_student_id");

                    b.Property<DateTimeOffset?>("MentorAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mentor_accepted_at");

                    b.Property<Guid>("MentorAlumnusId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentor_alumnus_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MenteeStudentId")
                        .HasDatabaseName("ix_mentorship_matches_mentee_student_id");

                    b.HasIndex("MentorAlumnusId")
                        .HasDatabaseName("ix_mentorship_matches_mentor_alumnus_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mentorship_matches_status");

                    b.ToTable("mentorship_matches", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Mentorship.MentorshipOptIn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_count");

                    b.Property<string>("Availability")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("availability");

                    b.Property<int>("CapacityLimit")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_limit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpertiseAreas")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("expertise_areas");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_mentorship_opt_ins_person_role");

                    b.ToTable("mentorship_opt_ins", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Infrastructure.Persistence.Inbox.ProcessedInboundEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "Source");

                    b.ToTable("processed_inbound_events", "alumni");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_event_type_processed_at");

                    b.ToTable("outbox_messages", "alumni");
                });

            modelBuilder.Entity("UMS.Modules.Alumni.Domain.Chapters.AlumniChapter", b =>
                {
                    b.OwnsMany("UMS.Modules.Alumni.Domain.Chapters.ChapterMembership", "Memberships", b1 =>
                        {
                            b1.Property<Guid>("ChapterId")
                                .HasColumnType("uuid")
                                .HasColumnName("chapter_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<Guid>("AlumnusId")
                                .HasColumnType("uuid")
                                .HasColumnName("alumnus_id");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.HasKey("ChapterId", "Ordinal");

                            b1.HasIndex("ChapterId", "AlumnusId")
                                .IsUnique()
                                .HasDatabaseName("ux_chapter_memberships_chapter_alumnus");

                            b1.ToTable("chapter_memberships", "alumni");

                            b1.WithOwner()
                                .HasForeignKey("ChapterId");
                        });

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
