// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Career.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Career.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CareerDbContext))]
    partial class CareerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("career")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Career.Domain.Applications.CareerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_reason");

                    b.Property<decimal?>("DeclaredCgpa")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("declared_cgpa");

                    b.Property<int?>("DeclaredYearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("declared_year_of_study");

                    b.Property<Guid?>("DriveId")
                        .HasColumnType("uuid")
                        .HasColumnName("drive_id");

                    b.Property<Guid?>("InternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<Guid?>("InterviewSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_slot_id");

                    b.Property<Guid>("ResumeArtifactIdSnapshot")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_artifact_id_snapshot");

                    b.Property<string>("ResumeFileNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resume_file_name_snapshot");

                    b.Property<Guid>("ResumeProfileIdSnapshot")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_profile_id_snapshot");

                    b.Property<DateTimeOffset>("ResumeSnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resume_snapshot_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DriveId")
                        .HasDatabaseName("ix_career_applications_drive_id");

                    b.HasIndex("InternshipId")
                        .HasDatabaseName("ix_career_applications_internship_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_career_applications_student_id");

                    b.HasIndex("StudentId", "DriveId")
                        .IsUnique()
                        .HasDatabaseName("ux_career_applications_student_drive")
                        .HasFilter("drive_id IS NOT NULL AND status NOT IN ('Withdrawn', 'Cancelled')");

                    b.HasIndex("StudentId", "InternshipId")
                        .IsUnique()
                        .HasDatabaseName("ux_career_applications_student_internship")
                        .HasFilter("internship_id IS NOT NULL AND status NOT IN ('Withdrawn', 'Cancelled')");

                    b.ToTable("career_applications", "career", t =>
                        {
                            t.HasCheckConstraint("ck_career_applications_target_xor", "(internship_id IS NOT NULL AND drive_id IS NULL) OR (internship_id IS NULL AND drive_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("UMS.Modules.Career.Domain.Drives.CampusRecruitmentDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_profile_id");

                    b.Property<DateTimeOffset>("RegistrationClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_closes_at");

                    b.Property<DateTimeOffset>("RegistrationOpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_opens_at");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid>("VenueRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_room_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EmployerProfileId")
                        .HasDatabaseName("ix_campus_recruitment_drives_employer_profile_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_campus_recruitment_drives_status");

                    b.ToTable("campus_recruitment_drives", "career");
                });

            modelBuilder.Entity("UMS.Modules.Career.Domain.Drives.InterviewSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BookedCount")
                        .HasColumnType("integer")
                        .HasColumnName("booked_count");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("DriveId")
                        .HasColumnType("uuid")
                        .HasColumnName("drive_id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("DriveId")
                        .HasDatabaseName("ix_interview_slots_drive_id");

                    b.ToTable("interview_slots", "career", t =>
                        {
                            t.HasCheckConstraint("ck_interview_slots_capacity", "booked_count <= capacity AND booked_count >= 0");
                        });
                });

            modelBuilder.Entity("UMS.Modules.Career.Domain.Employers.EmployerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("VerificationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("verification_note");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_employer_profiles_is_archived");

                    b.ToTable("employer_profiles", "career");
                });

            modelBuilder.Entity("UMS.Modules.Career.Domain.Internships.Internship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApplicationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("application_deadline");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EligibilityMinCgpa")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("eligibility_min_cgpa");

                    b.Property<int?>("EligibilityMinYearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("eligibility_min_year_of_study");

                    b.Property<Guid>("EmployerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_profile_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StipendNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stipend_note");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("withdrawal_reason");

                    b.PrimitiveCollection<List<Guid>>("_eligibilityProgramIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("eligibility_program_ids");

                    b.HasKey("Id");

                    b.HasIndex("EmployerProfileId")
                        .HasDatabaseName("ix_internships_employer_profile_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_internships_status");

                    b.HasIndex("Status", "ApplicationDeadline")
                        .HasDatabaseName("ix_internships_status_deadline");

                    b.ToTable("internships", "career");
                });

            modelBuilder.Entity("UMS.Modules.Career.Domain.ResumeProfiles.ResumeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_resume_profiles_student_id");

                    b.HasIndex("StudentId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_resume_profiles_student_default")
                        .HasFilter("is_default = true AND is_deleted = false");

                    b.ToTable("resume_profiles", "career");
                });

            modelBuilder.Entity("UMS.Modules.Career.Infrastructure.Persistence.Inbox.ProcessedInboundEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "Source");

                    b.ToTable("processed_inbound_events", "career");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_event_type_processed_at");

                    b.ToTable("outbox_messages", "career");
                });
#pragma warning restore 612, 618
        }
    }
}
