// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Admission.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Admission.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdmissionDbContext))]
    [Migration("20260907091303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admission")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("application_number_seq", "admission");

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Applicants.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("given_name");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mobile_verified");

                    b.Property<string>("Mobile")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile");

                    b.Property<int>("PendingOtpAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("pending_otp_attempts");

                    b.Property<string>("PendingOtpChannel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pending_otp_channel");

                    b.Property<DateTimeOffset?>("PendingOtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_otp_expires_at");

                    b.Property<string>("PendingOtpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pending_otp_hash");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_applicants_identity_user_id");

                    b.ToTable("applicants", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdmitCardDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("admit_card_document_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_id");

                    b.Property<Guid?>("ApplicationFeeInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_fee_invoice_id");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_number");

                    b.Property<Guid?>("AssignedTestSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_test_slot_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("ConfirmationFeeInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmation_fee_invoice_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsApplicationFeePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_application_fee_paid");

                    b.Property<bool>("IsConfirmationFeePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmation_fee_paid");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("RollNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("roll_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFeeInvoiceId")
                        .HasDatabaseName("ix_applications_application_fee_invoice_id");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_applications_application_number")
                        .HasFilter("application_number IS NOT NULL");

                    b.HasIndex("ConfirmationFeeInvoiceId")
                        .HasDatabaseName("ix_applications_confirmation_fee_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_applications_status");

                    b.HasIndex("ApplicantId", "CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_applications_applicant_campaign");

                    b.ToTable("applications", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Campaigns.AdmissionCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationFeeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application_fee_type");

                    b.Property<string>("ConfirmationFeeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmation_fee_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsConfigurationLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_configuration_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("ProgramIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("program_ids");

                    b.Property<string>("RequiredDocumentTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_document_types");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("admission_campaigns", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.ExamAttempts.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_test_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_id");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("evaluation_status");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal?>("ObjectiveScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("objective_score");

                    b.Property<string>("ProctoringSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proctoring_session_id");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("roll_number");

                    b.Property<long>("SeedValue")
                        .HasColumnType("bigint")
                        .HasColumnName("seed_value");

                    b.Property<string>("SelectedQuestionIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_question_ids");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("SubjectiveScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("subjective_score");

                    b.Property<string>("SubmissionSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("submission_source");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TestSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_slot_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId", "AdmissionTestId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_attempts_applicant_test");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_exam_attempts_status_expires_at");

                    b.ToTable("exam_attempts", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.MeritLists.MeritList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_merit_lists_campaign_id");

                    b.ToTable("merit_lists", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Publishing.PublishJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_result_id");

                    b.Property<Guid?>("CacheCursor")
                        .HasColumnType("uuid")
                        .HasColumnName("cache_cursor");

                    b.Property<int>("CacheProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("cache_processed_count");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("FanOutCursor")
                        .HasColumnType("uuid")
                        .HasColumnName("fan_out_cursor");

                    b.Property<int>("FanOutProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("fan_out_processed_count");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionResultId")
                        .HasDatabaseName("ix_publish_jobs_admission_result_id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("ix_publish_jobs_stage");

                    b.ToTable("publish_jobs", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Results.AdmissionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int>("CorrectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("correction_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("locked_by_user_id");

                    b.Property<Guid>("MeritListId")
                        .HasColumnType("uuid")
                        .HasColumnName("merit_list_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<DateTimeOffset?>("PublishingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publishing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_admission_results_campaign_id");

                    b.ToTable("admission_results", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Tests.AdmissionTest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_admission_tests_campaign_id");

                    b.ToTable("admission_tests", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Infrastructure.Persistence.Inbox.ProcessedInboundEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("processed_inbound_events", "admission");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_outbox_messages_event_type");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "admission");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Applicants.Applicant", b =>
                {
                    b.OwnsMany("UMS.Modules.Admission.Domain.Applicants.AcademicRecord", "AcademicHistory", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid")
                                .HasColumnName("applicant_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<string>("Board")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("board");

                            b1.Property<string>("ExamName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("exam_name");

                            b1.Property<int>("PassingYear")
                                .HasColumnType("integer")
                                .HasColumnName("passing_year");

                            b1.HasKey("ApplicantId", "Ordinal");

                            b1.ToTable("applicant_academic_records", "admission");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");

                            b1.OwnsOne("UMS.Shared.Domain.PercentageOrGpa", "Score", b2 =>
                                {
                                    b2.Property<Guid>("AcademicRecordApplicantId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("AcademicRecordOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Scale")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("score_scale");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("score");

                                    b2.HasKey("AcademicRecordApplicantId", "AcademicRecordOrdinal");

                                    b2.ToTable("applicant_academic_records", "admission");

                                    b2.WithOwner()
                                        .HasForeignKey("AcademicRecordApplicantId", "AcademicRecordOrdinal");
                                });

                            b1.Navigation("Score")
                                .IsRequired();
                        });

                    b.Navigation("AcademicHistory");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Applications.Application", b =>
                {
                    b.OwnsMany("UMS.Modules.Admission.Domain.Applications.ApplicationDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("application_id");

                            b1.Property<string>("DocumentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("document_type");

                            b1.Property<string>("FileReference")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("file_reference");

                            b1.Property<string>("RejectionReason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("rejection_reason");

                            b1.Property<DateTimeOffset?>("ReviewedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reviewed_at");

                            b1.Property<Guid?>("ReviewedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("reviewed_by_user_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("status");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("application_documents", "admission");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("UMS.Modules.Admission.Domain.Applications.ProgramChoice", "ProgramChoices", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("application_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid")
                                .HasColumnName("program_id");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer")
                                .HasColumnName("rank");

                            b1.HasKey("ApplicationId", "Ordinal");

                            b1.ToTable("application_program_choices", "admission");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Documents");

                    b.Navigation("ProgramChoices");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Campaigns.AdmissionCampaign", b =>
                {
                    b.OwnsOne("UMS.Shared.Domain.DateRange", "ApplicationWindow", b1 =>
                        {
                            b1.Property<Guid>("AdmissionCampaignId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("application_window_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("application_window_start");

                            b1.HasKey("AdmissionCampaignId");

                            b1.ToTable("admission_campaigns", "admission");

                            b1.WithOwner()
                                .HasForeignKey("AdmissionCampaignId");
                        });

                    b.OwnsMany("UMS.Modules.Admission.Domain.Campaigns.EligibilityRule", "EligibilityRules", b1 =>
                        {
                            b1.Property<Guid>("CampaignId")
                                .HasColumnType("uuid")
                                .HasColumnName("campaign_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid")
                                .HasColumnName("program_id");

                            b1.Property<string>("RequiredBoard")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("required_board");

                            b1.HasKey("CampaignId", "Ordinal");

                            b1.ToTable("campaign_eligibility_rules", "admission");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");

                            b1.OwnsOne("UMS.Shared.Domain.PercentageOrGpa", "MinimumScore", b2 =>
                                {
                                    b2.Property<Guid>("EligibilityRuleCampaignId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("EligibilityRuleOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Scale")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("min_score_scale");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("min_score");

                                    b2.HasKey("EligibilityRuleCampaignId", "EligibilityRuleOrdinal");

                                    b2.ToTable("campaign_eligibility_rules", "admission");

                                    b2.WithOwner()
                                        .HasForeignKey("EligibilityRuleCampaignId", "EligibilityRuleOrdinal");
                                });

                            b1.Navigation("MinimumScore")
                                .IsRequired();
                        });

                    b.OwnsMany("UMS.Modules.Admission.Domain.Campaigns.SeatQuota", "SeatQuotas", b1 =>
                        {
                            b1.Property<Guid>("CampaignId")
                                .HasColumnType("uuid")
                                .HasColumnName("campaign_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid")
                                .HasColumnName("program_id");

                            b1.Property<int>("Quota")
                                .HasColumnType("integer")
                                .HasColumnName("quota");

                            b1.HasKey("CampaignId", "Ordinal");

                            b1.HasIndex("CampaignId", "ProgramId")
                                .IsUnique();

                            b1.ToTable("campaign_seat_quotas", "admission");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.Navigation("ApplicationWindow")
                        .IsRequired();

                    b.Navigation("EligibilityRules");

                    b.Navigation("SeatQuotas");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.ExamAttempts.ExamAttempt", b =>
                {
                    b.OwnsMany("UMS.Modules.Admission.Domain.ExamAttempts.ExamAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("ExamAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("exam_attempt_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<DateTimeOffset>("AnsweredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("answered_at");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<int?>("SelectedOptionIndex")
                                .HasColumnType("integer")
                                .HasColumnName("selected_option_index");

                            b1.Property<string>("SubjectiveText")
                                .HasColumnType("text")
                                .HasColumnName("subjective_text");

                            b1.HasKey("ExamAttemptId", "Ordinal");

                            b1.HasIndex("ExamAttemptId", "QuestionId")
                                .IsUnique();

                            b1.ToTable("exam_attempt_answers", "admission");

                            b1.WithOwner()
                                .HasForeignKey("ExamAttemptId");
                        });

                    b.OwnsMany("UMS.Modules.Admission.Domain.ExamAttempts.IntegrityFlag", "IntegrityFlags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AnomalyType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("anomaly_type");

                            b1.Property<decimal>("ConfidenceScore")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("confidence_score");

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("details");

                            b1.Property<Guid>("ExamAttemptId")
                                .HasColumnType("uuid")
                                .HasColumnName("exam_attempt_id");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("outcome");

                            b1.Property<DateTimeOffset>("RaisedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("raised_at");

                            b1.Property<string>("ReviewNotes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("review_notes");

                            b1.Property<DateTimeOffset?>("ReviewedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reviewed_at");

                            b1.Property<Guid?>("ReviewedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("reviewed_by_user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ExamAttemptId");

                            b1.ToTable("exam_attempt_integrity_flags", "admission");

                            b1.WithOwner()
                                .HasForeignKey("ExamAttemptId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("IntegrityFlags");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.MeritLists.MeritList", b =>
                {
                    b.OwnsMany("UMS.Modules.Admission.Domain.MeritLists.MeritListEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("MeritListId")
                                .HasColumnType("uuid")
                                .HasColumnName("merit_list_id");

                            b1.Property<Guid>("ApplicantId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("applicant_id");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("application_id");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("outcome");

                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid")
                                .HasColumnName("program_id");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer")
                                .HasColumnName("rank");

                            b1.Property<decimal>("Score")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("score");

                            b1.Property<int?>("WaitlistRank")
                                .HasColumnType("integer")
                                .HasColumnName("waitlist_rank");

                            b1.HasKey("MeritListId", "ApplicantId");

                            b1.ToTable("merit_list_entries", "admission");

                            b1.WithOwner()
                                .HasForeignKey("MeritListId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Results.AdmissionResult", b =>
                {
                    b.OwnsMany("UMS.Modules.Admission.Domain.Results.AdmissionResultEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("AdmissionResultId")
                                .HasColumnType("uuid")
                                .HasColumnName("admission_result_id");

                            b1.Property<Guid>("ApplicantId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("applicant_id");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("application_id");

                            b1.Property<int>("MeritRank")
                                .HasColumnType("integer")
                                .HasColumnName("merit_rank");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("outcome");

                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid")
                                .HasColumnName("program_id");

                            b1.Property<int?>("WaitlistRank")
                                .HasColumnType("integer")
                                .HasColumnName("waitlist_rank");

                            b1.HasKey("AdmissionResultId", "ApplicantId");

                            b1.ToTable("admission_result_entries", "admission");

                            b1.WithOwner()
                                .HasForeignKey("AdmissionResultId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("UMS.Modules.Admission.Domain.Tests.AdmissionTest", b =>
                {
                    b.OwnsMany("UMS.Modules.Admission.Domain.Tests.QuestionBankEntry", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AdmissionTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("admission_test_id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("category");

                            b1.Property<int?>("CorrectOptionIndex")
                                .HasColumnType("integer")
                                .HasColumnName("correct_option_index");

                            b1.Property<string>("Difficulty")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("difficulty");

                            b1.Property<bool>("IsSubjective")
                                .HasColumnType("boolean")
                                .HasColumnName("is_subjective");

                            b1.Property<decimal>("MaxScore")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("max_score");

                            b1.Property<string>("Options")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("options");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.HasKey("Id");

                            b1.HasIndex("AdmissionTestId");

                            b1.ToTable("admission_test_questions", "admission");

                            b1.WithOwner()
                                .HasForeignKey("AdmissionTestId");
                        });

                    b.OwnsMany("UMS.Modules.Admission.Domain.Tests.QuestionSelectionRule", "SelectionRules", b1 =>
                        {
                            b1.Property<Guid>("AdmissionTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("admission_test_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("count");

                            b1.Property<string>("Difficulty")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("difficulty");

                            b1.HasKey("AdmissionTestId", "Ordinal");

                            b1.HasIndex("AdmissionTestId", "Difficulty")
                                .IsUnique();

                            b1.ToTable("admission_test_selection_rules", "admission");

                            b1.WithOwner()
                                .HasForeignKey("AdmissionTestId");
                        });

                    b.OwnsMany("UMS.Modules.Admission.Domain.Tests.TestSlot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AdmissionTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("admission_test_id");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer")
                                .HasColumnName("capacity");

                            b1.Property<DateTimeOffset>("EndAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_at");

                            b1.Property<int>("RemainingSeats")
                                .HasColumnType("integer")
                                .HasColumnName("remaining_seats");

                            b1.Property<DateTimeOffset>("StartAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_at");

                            b1.HasKey("Id");

                            b1.HasIndex("AdmissionTestId");

                            b1.ToTable("admission_test_slots", "admission");

                            b1.WithOwner()
                                .HasForeignKey("AdmissionTestId");
                        });

                    b.Navigation("Questions");

                    b.Navigation("SelectionRules");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
