// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Faculty.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Faculty.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FacultyDbContext))]
    partial class FacultyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("faculty")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Faculty.Domain.CourseAssignments.CourseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("faculty_member_id");

                    b.Property<DateTimeOffset>("LastAppliedEventOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_applied_event_occurred_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .HasDatabaseName("ix_course_assignments_faculty_member_id");

                    b.HasIndex("FacultyMemberId", "CourseOfferingId")
                        .IsUnique()
                        .HasDatabaseName("ux_course_assignments_faculty_member_id_course_offering_id");

                    b.ToTable("course_assignments", "faculty");
                });

            modelBuilder.Entity("UMS.Modules.Faculty.Domain.FacultyMembers.FacultyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uuid")
                        .HasColumnName("designation_id");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<bool>("IsDepartmentHead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_department_head");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_faculty_members_department_id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_faculty_members_employee_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_faculty_members_user_id");

                    b.ToTable("faculty_members", "faculty");
                });

            modelBuilder.Entity("UMS.Modules.Faculty.Domain.LeaveRequests.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("faculty_member_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<bool>("RoutedDirectlyToAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("routed_directly_to_authority");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SupportingDocumentReference")
                        .HasColumnType("uuid")
                        .HasColumnName("supporting_document_reference");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .HasDatabaseName("ix_leave_requests_faculty_member_id");

                    b.ToTable("leave_requests", "faculty");
                });

            modelBuilder.Entity("UMS.Modules.Faculty.Domain.ResearchProfiles.ResearchProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FacultyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("faculty_member_id");

                    b.Property<string>("Grants")
                        .HasColumnType("text")
                        .HasColumnName("grants");

                    b.Property<string>("OngoingResearch")
                        .HasColumnType("text")
                        .HasColumnName("ongoing_research");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FacultyMemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_research_profiles_faculty_member_id");

                    b.ToTable("research_profiles", "faculty");
                });

            modelBuilder.Entity("UMS.Modules.Faculty.Infrastructure.Persistence.ProcessedInboundEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("processed_inbound_events", "faculty");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "faculty");
                });

            modelBuilder.Entity("UMS.Modules.Faculty.Domain.LeaveRequests.LeaveRequest", b =>
                {
                    b.OwnsMany("UMS.Modules.Faculty.Domain.Translations.TextTranslation", "ReasonTranslations", b1 =>
                        {
                            b1.Property<Guid>("LeaveRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("leave_request_id");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.HasKey("LeaveRequestId", "LanguageCode");

                            b1.ToTable("leave_request_reason_translations", "faculty");

                            b1.WithOwner()
                                .HasForeignKey("LeaveRequestId");
                        });

                    b.Navigation("ReasonTranslations");
                });

            modelBuilder.Entity("UMS.Modules.Faculty.Domain.ResearchProfiles.ResearchProfile", b =>
                {
                    b.OwnsMany("UMS.Modules.Faculty.Domain.ResearchProfiles.Publication", "Publications", b1 =>
                        {
                            b1.Property<Guid>("ResearchProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("research_profile_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("title");

                            b1.Property<string>("Url")
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.Property<string>("Venue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("venue");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("year");

                            b1.HasKey("ResearchProfileId", "Id");

                            b1.ToTable("research_profile_publications", "faculty");

                            b1.WithOwner()
                                .HasForeignKey("ResearchProfileId");
                        });

                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
