<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UMS.Modules\Admission\UMS.Modules.Admission.Domain\UMS.Modules.Admission.Domain.csproj" />
    <ProjectReference Include="..\..\src\UMS.Modules\Admission\UMS.Modules.Admission.Application\UMS.Modules.Admission.Application.csproj" />
    <ProjectReference Include="..\..\src\Shared\UMS.Shared.ErrorHandling\UMS.Shared.ErrorHandling.csproj" />
    <ProjectReference Include="..\..\src\Shared\UMS.Shared.Domain\UMS.Shared.Domain.csproj" />
  </ItemGroup>

</Project>
