// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Organization.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260904055941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Campuses.Campus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_campuses_university_id");

                    b.HasIndex("UniversityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_campuses_university_id_name");

                    b.ToTable("campuses", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("faculty_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId")
                        .HasDatabaseName("ix_departments_faculty_id");

                    b.HasIndex("FacultyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_departments_faculty_id_name");

                    b.ToTable("departments", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Designations.Designation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("designations", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Facilities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_buildings_campus_id");

                    b.ToTable("buildings", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Facilities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RoomType")
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_rooms_building_id");

                    b.ToTable("rooms", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Faculties.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_faculties_campus_id");

                    b.HasIndex("CampusId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_faculties_campus_id_name");

                    b.ToTable("faculties", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Programs.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_programs_department_id");

                    b.HasIndex("DepartmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_programs_department_id_name");

                    b.ToTable("programs", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Universities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("universities", "organization");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "organization");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Departments.Department", b =>
                {
                    b.OwnsMany("UMS.Modules.Organization.Domain.Translations.NameTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("DepartmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("department_id");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("DepartmentId", "LanguageCode");

                            b1.ToTable("department_translations", "organization");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Designations.Designation", b =>
                {
                    b.OwnsMany("UMS.Modules.Organization.Domain.Translations.NameTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("DesignationId")
                                .HasColumnType("uuid")
                                .HasColumnName("designation_id");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("title");

                            b1.HasKey("DesignationId", "LanguageCode");

                            b1.ToTable("designation_translations", "organization");

                            b1.WithOwner()
                                .HasForeignKey("DesignationId");
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Faculties.Faculty", b =>
                {
                    b.OwnsMany("UMS.Modules.Organization.Domain.Translations.NameTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("FacultyId")
                                .HasColumnType("uuid")
                                .HasColumnName("faculty_id");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("FacultyId", "LanguageCode");

                            b1.ToTable("faculty_translations", "organization");

                            b1.WithOwner()
                                .HasForeignKey("FacultyId");
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("UMS.Modules.Organization.Domain.Programs.Program", b =>
                {
                    b.OwnsMany("UMS.Modules.Organization.Domain.Translations.NameTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("ProgramId")
                                .HasColumnType("uuid")
                                .HasColumnName("program_id");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("ProgramId", "LanguageCode");

                            b1.ToTable("program_translations", "organization");

                            b1.WithOwner()
                                .HasForeignKey("ProgramId");
                        });

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
