// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Notifications.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260904094924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Preferences.ChannelSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset>("SuppressedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppressed_at");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ux_channel_suppressions_recipient_channel");

                    b.ToTable("channel_suppressions", "notifications");
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Preferences.RecipientNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<bool>("OptedOut")
                        .HasColumnType("boolean")
                        .HasColumnName("opted_out");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ux_recipient_notification_preferences_recipient_category");

                    b.ToTable("recipient_notification_preferences", "notifications");
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Requests.NotificationDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeadLetterReason")
                        .HasColumnType("integer")
                        .HasColumnName("dead_letter_reason");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset?>("InFlightSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("in_flight_since");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_request_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("RenderedBody")
                        .HasColumnType("text")
                        .HasColumnName("rendered_body");

                    b.Property<string>("RenderedDeepLink")
                        .HasColumnType("text")
                        .HasColumnName("rendered_deep_link");

                    b.Property<string>("RenderedSubject")
                        .HasColumnType("text")
                        .HasColumnName("rendered_subject");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRequestId")
                        .HasDatabaseName("ix_notification_delivery_attempts_request");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_notification_delivery_attempts_status");

                    b.HasIndex("Channel", "ProviderMessageId")
                        .HasDatabaseName("ix_notification_delivery_attempts_provider_message");

                    b.HasIndex("Channel", "Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notification_delivery_attempts_dispatch");

                    b.ToTable("notification_delivery_attempts", "notifications");
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Requests.NotificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LanguageOverride")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_override");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_module");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notification_requests_recipient");

                    b.HasIndex("SourceModule", "EventType", "SourceEntityId", "RecipientId")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_requests_dedupe");

                    b.ToTable("notification_requests", "notifications");
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Templates.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ux_templates_event_type_channel");

                    b.ToTable("templates", "notifications");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_notifications_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "notifications");
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Requests.NotificationDeliveryAttempt", b =>
                {
                    b.HasOne("UMS.Modules.Notifications.Domain.Requests.NotificationRequest", null)
                        .WithMany("Attempts")
                        .HasForeignKey("NotificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Templates.Template", b =>
                {
                    b.OwnsMany("UMS.Modules.Notifications.Domain.Templates.TemplateTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<string>("DeepLink")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("deep_link");

                            b1.Property<string>("LanguageCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("language_code");

                            b1.Property<string>("PushTitle")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("push_title");

                            b1.Property<string>("Subject")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("subject");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("template_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("template_id", "LanguageCode")
                                .IsUnique()
                                .HasDatabaseName("ux_template_translations_template_language");

                            b1.ToTable("template_translations", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("template_id");
                        });

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("UMS.Modules.Notifications.Domain.Requests.NotificationRequest", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
