// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Identity.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Identity.Domain.Permissions.PermissionCatalogEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OwningModule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owning_module");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.HasKey("Key");

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("UMS.Modules.Identity.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("UMS.Modules.Identity.Domain.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .HasColumnType("text")
                        .HasColumnName("created_from_ip");

                    b.Property<DateTimeOffset>("CurrentRefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_refresh_token_expires_at");

                    b.Property<string>("CurrentRefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_refresh_token_hash");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("PreviousRefreshTokenConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_refresh_token_consumed_at");

                    b.Property<string>("PreviousRefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("previous_refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", "identity");
                });

            modelBuilder.Entity("UMS.Modules.Identity.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("Mobile")
                        .HasColumnType("citext")
                        .HasColumnName("mobile");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("UniversityId")
                        .HasColumnType("citext")
                        .HasColumnName("university_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Mobile")
                        .IsUnique()
                        .HasDatabaseName("ux_users_mobile")
                        .HasFilter("\"mobile\" IS NOT NULL");

                    b.HasIndex("UniversityId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_university_id")
                        .HasFilter("\"university_id\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("UMS.Modules.Identity.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "identity");
                });

            modelBuilder.Entity("UMS.Modules.Identity.Domain.Users.User", b =>
                {
                    b.OwnsOne("UMS.Modules.Identity.Domain.Users.Credential", "Credential", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password_algorithm");

                            b1.Property<DateTimeOffset>("ChangedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("password_changed_at");

                            b1.Property<string>("PasswordHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("UMS.Modules.Identity.Domain.Users.UserRoleAssignment", "RoleAssignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AssignedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("assigned_at");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.Property<Guid?>("ScopeNode")
                                .HasColumnType("uuid")
                                .HasColumnName("organization_node_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId", "RoleId", "ScopeNode")
                                .HasDatabaseName("ix_user_role_assignments_user_role_scope");

                            b1.ToTable("user_role_assignments", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("UMS.Shared.Domain.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("family_name");

                            b1.Property<string>("FamilyNameBn")
                                .HasColumnType("text")
                                .HasColumnName("family_name_bn");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("given_name");

                            b1.Property<string>("GivenNameBn")
                                .HasColumnType("text")
                                .HasColumnName("given_name_bn");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Credential")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
