// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Learning.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Learning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    partial class LearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Learning.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowResubmission")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_resubmission");

                    b.Property<string>("AllowedSubmissionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("allowed_submission_type");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer")
                        .HasColumnName("max_points");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .HasDatabaseName("ix_assignments_course_offering_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_assignments_status");

                    b.ToTable("assignments", "learning");
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.Discussions.DiscussionThread", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .HasDatabaseName("ix_discussion_threads_course_offering_id");

                    b.ToTable("discussion_threads", "learning");
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.LectureMaterials.LectureMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("material_type");

                    b.Property<string>("ModuleGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("module_group");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId", "ModuleGroup", "SortOrder")
                        .HasDatabaseName("ix_lecture_materials_offering_group_order");

                    b.ToTable("lecture_materials", "learning");
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppliedExtensionId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_extension_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset?>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<Guid?>("EvaluatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluated_by_user_id");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_late");

                    b.Property<decimal>("LatePenaltyPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("late_penalty_percentage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<Guid?>("SupersededBySubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_submission_id");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .HasDatabaseName("ix_submissions_course_offering_id");

                    b.HasIndex("AssignmentId", "Status")
                        .HasDatabaseName("ix_submissions_assignment_status");

                    b.HasIndex("AssignmentId", "StudentId")
                        .HasDatabaseName("ix_submissions_assignment_student");

                    b.ToTable("submissions", "learning");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_outbox_messages_event_type");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "learning");
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.Assignments.Assignment", b =>
                {
                    b.OwnsMany("UMS.Modules.Learning.Domain.Assignments.SubmissionExtension", "Extensions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignment_id");

                            b1.Property<DateTimeOffset>("ExtendedDeadline")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("extended_deadline");

                            b1.Property<DateTimeOffset>("GrantedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("granted_at");

                            b1.Property<Guid>("GrantedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("granted_by_user_id");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid")
                                .HasColumnName("student_id");

                            b1.Property<Guid>("StudentUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("student_user_id");

                            b1.Property<bool>("WaivesLatePenalty")
                                .HasColumnType("boolean")
                                .HasColumnName("waives_late_penalty");

                            b1.HasKey("Id");

                            b1.HasIndex("AssignmentId", "StudentId")
                                .IsUnique()
                                .HasDatabaseName("ux_submission_extensions_assignment_student");

                            b1.ToTable("submission_extensions", "learning");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.OwnsOne("UMS.Modules.Learning.Domain.Assignments.SubmissionWindow", "SubmissionWindow", b1 =>
                        {
                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Deadline")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_deadline");

                            b1.Property<TimeSpan>("GracePeriod")
                                .HasColumnType("interval")
                                .HasColumnName("window_grace_period");

                            b1.Property<DateTimeOffset>("HardCloseAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_hard_close_at");

                            b1.Property<string>("LatePenaltyPolicy")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("window_late_penalty_tiers");

                            b1.Property<DateTimeOffset>("OpensAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_opens_at");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("assignments", "learning");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("Extensions");

                    b.Navigation("SubmissionWindow")
                        .IsRequired();
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.Discussions.DiscussionThread", b =>
                {
                    b.OwnsMany("UMS.Modules.Learning.Domain.Discussions.DiscussionPost", "Posts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AuthorUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_user_id");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("DiscussionThreadId")
                                .HasColumnType("uuid")
                                .HasColumnName("discussion_thread_id");

                            b1.Property<string>("ModerationStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("moderation_status");

                            b1.Property<Guid?>("ParentPostId")
                                .HasColumnType("uuid")
                                .HasColumnName("parent_post_id");

                            b1.Property<DateTimeOffset?>("RemovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removed_at");

                            b1.Property<Guid?>("RemovedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("removed_by_user_id");

                            b1.Property<string>("RemovedReason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("removed_reason");

                            b1.Property<DateTimeOffset?>("RestoredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("restored_at");

                            b1.Property<Guid?>("RestoredByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("restored_by_user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("DiscussionThreadId");

                            b1.ToTable("discussion_posts", "learning");

                            b1.WithOwner()
                                .HasForeignKey("DiscussionThreadId");
                        });

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.LectureMaterials.LectureMaterial", b =>
                {
                    b.OwnsMany("UMS.Modules.Learning.Domain.LectureMaterials.LectureMaterialTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("LectureMaterialId")
                                .HasColumnType("uuid")
                                .HasColumnName("lecture_material_id");

                            b1.Property<string>("Language")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("language_code");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("title");

                            b1.HasKey("LectureMaterialId", "Language");

                            b1.ToTable("lecture_material_translations", "learning");

                            b1.WithOwner()
                                .HasForeignKey("LectureMaterialId");
                        });

                    b.OwnsMany("UMS.Modules.Learning.Domain.LectureMaterials.LectureMaterialVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("ArtifactId")
                                .HasColumnType("uuid")
                                .HasColumnName("artifact_id");

                            b1.Property<string>("ChangeNote")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("change_note");

                            b1.Property<string>("ExternalUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("external_url");

                            b1.Property<Guid>("LectureMaterialId")
                                .HasColumnType("uuid")
                                .HasColumnName("lecture_material_id");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<Guid>("PublishedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("published_by_user_id");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("version_number");

                            b1.HasKey("Id");

                            b1.HasIndex("LectureMaterialId", "VersionNumber")
                                .IsUnique()
                                .HasDatabaseName("ux_lecture_material_versions_material_number");

                            b1.ToTable("lecture_material_versions", "learning");

                            b1.WithOwner()
                                .HasForeignKey("LectureMaterialId");
                        });

                    b.Navigation("Translations");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("UMS.Modules.Learning.Domain.Submissions.Submission", b =>
                {
                    b.OwnsMany("UMS.Modules.Learning.Domain.PlagiarismChecks.PlagiarismCheck", "PlagiarismChecks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("AttemptCount")
                                .HasColumnType("integer")
                                .HasColumnName("attempt_count");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("failure_reason");

                            b1.Property<DateTimeOffset>("QueuedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("queued_at");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("status");

                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("submission_id");

                            b1.HasKey("Id");

                            b1.HasIndex("Status")
                                .HasDatabaseName("ix_plagiarism_checks_status");

                            b1.HasIndex("SubmissionId");

                            b1.ToTable("plagiarism_checks", "learning");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");

                            b1.OwnsOne("UMS.Modules.Learning.Domain.PlagiarismChecks.PlagiarismScore", "Score", b2 =>
                                {
                                    b2.Property<Guid>("PlagiarismCheckId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("MatchedSourceSummary")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("score_matched_source_summary");

                                    b2.Property<string>("ProviderName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("score_provider_name");

                                    b2.Property<decimal>("SimilarityPercentage")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("score_similarity_percentage");

                                    b2.HasKey("PlagiarismCheckId");

                                    b2.ToTable("plagiarism_checks", "learning");

                                    b2.WithOwner()
                                        .HasForeignKey("PlagiarismCheckId");
                                });

                            b1.Navigation("Score");
                        });

                    b.OwnsOne("UMS.Modules.Learning.Domain.Submissions.AssignmentScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AppliedLatePenaltyPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("score_applied_late_penalty_percentage");

                            b1.Property<decimal>("AwardedPoints")
                                .HasPrecision(9, 2)
                                .HasColumnType("numeric(9,2)")
                                .HasColumnName("score_awarded_points");

                            b1.Property<string>("Feedback")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("score_feedback");

                            b1.Property<int>("MaxPoints")
                                .HasColumnType("integer")
                                .HasColumnName("score_max_points");

                            b1.Property<decimal>("RawPoints")
                                .HasPrecision(9, 2)
                                .HasColumnType("numeric(9,2)")
                                .HasColumnName("score_raw_points");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "learning");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.OwnsMany("UMS.Modules.Learning.Domain.Submissions.SubmissionFile", "Files", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("submission_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<Guid>("ArtifactId")
                                .HasColumnType("uuid")
                                .HasColumnName("artifact_id");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("file_name");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mime_type");

                            b1.HasKey("SubmissionId", "Ordinal");

                            b1.ToTable("submission_files", "learning");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("Files");

                    b.Navigation("PlagiarismChecks");

                    b.Navigation("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
