// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Hostel.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Hostel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HostelDbContext))]
    partial class HostelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hostel")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Allocations.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<string>("CheckOutKind")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("check_out_kind");

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_out_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("FeeGraceDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fee_grace_deadline");

                    b.Property<DateTimeOffset?>("FeePaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fee_paid_at");

                    b.Property<Guid>("HostelApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("hostel_application_id");

                    b.Property<Guid>("HostelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hostel_id");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("RefundRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("refund_requested");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BedId")
                        .IsUnique()
                        .HasDatabaseName("ux_allocations_bed_nonterminal")
                        .HasFilter("status IN ('Pending', 'FeePaid', 'Active')");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_allocations_invoice_id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("ux_allocations_student_nonterminal")
                        .HasFilter("status IN ('Pending', 'FeePaid', 'Active')");

                    b.HasIndex("Status", "FeeGraceDeadline")
                        .HasDatabaseName("ix_allocations_status_grace_deadline");

                    b.ToTable("allocations", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Allocations.AllocationReviewFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceEventReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_event_reference");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId")
                        .HasDatabaseName("ix_allocation_review_flags_allocation_id");

                    b.ToTable("allocation_review_flags", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.ApplicationWindows.ApplicationWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EligibilityRules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("eligibility_rules");

                    b.Property<string>("EligibleProgramIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("eligible_program_ids");

                    b.Property<string>("EligibleYears")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("eligible_years");

                    b.Property<DateTimeOffset>("OpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opens_at");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rules_version");

                    b.Property<string>("SessionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_label");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("application_windows", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Applications.HostelApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<Guid>("ApplicationWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_window_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_reason");

                    b.Property<decimal?>("EligibilityScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("eligibility_score");

                    b.Property<bool>("HasFinancialNeed")
                        .HasColumnType("boolean")
                        .HasColumnName("has_financial_need");

                    b.Property<decimal?>("HomeDistrictDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("home_district_distance_km");

                    b.Property<bool?>("IsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eligible");

                    b.Property<int?>("RankPosition")
                        .HasColumnType("integer")
                        .HasColumnName("rank_position");

                    b.Property<DateTimeOffset?>("RankedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ranked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_study");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationWindowId", "Status")
                        .HasDatabaseName("ix_hostel_applications_window_status");

                    b.HasIndex("StudentId", "ApplicationWindowId")
                        .IsUnique()
                        .HasDatabaseName("ux_hostel_applications_student_window_open")
                        .HasFilter("status IN ('Draft', 'Submitted', 'Ranked', 'Waitlisted', 'Approved')");

                    b.ToTable("hostel_applications", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Complaints.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_complaints_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_complaints_student_id");

                    b.HasIndex("StudentId", "AllocationId", "CreatedAt")
                        .HasDatabaseName("ix_complaints_dedupe_window");

                    b.ToTable("complaints", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Hostels.Bed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_beds_room_id");

                    b.HasIndex("RoomId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ux_beds_room_label");

                    b.ToTable("beds", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Hostels.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hostel_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HostelId")
                        .HasDatabaseName("ix_buildings_hostel_id");

                    b.ToTable("buildings", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Hostels.Hostel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("hostels", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Hostels.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hostel_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_rooms_building_id");

                    b.HasIndex("BuildingId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_rooms_building_room_number");

                    b.HasIndex("HostelId", "Type")
                        .HasDatabaseName("ix_rooms_hostel_id_type");

                    b.ToTable("rooms", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Infrastructure.Persistence.Inbox.ProcessedInboundEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "Source");

                    b.ToTable("processed_inbound_events", "hostel");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_outbox_messages_event_type");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "hostel");
                });

            modelBuilder.Entity("UMS.Modules.Hostel.Domain.Applications.HostelApplication", b =>
                {
                    b.OwnsMany("UMS.Modules.Hostel.Domain.Applications.HostelPreference", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("HostelApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("hostel_application_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<Guid>("HostelId")
                                .HasColumnType("uuid")
                                .HasColumnName("hostel_id");

                            b1.Property<string>("PreferredRoomType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("preferred_room_type");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer")
                                .HasColumnName("rank");

                            b1.HasKey("HostelApplicationId", "Ordinal");

                            b1.ToTable("hostel_application_preferences", "hostel");

                            b1.WithOwner()
                                .HasForeignKey("HostelApplicationId");
                        });

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
