// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Student.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Student.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260907112249_AddStudentRequestsAndBulkImport")]
    partial class AddStudentRequestsAndBulkImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("student")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Student.Domain.BulkImport.StudentBulkImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<int>("InvalidRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_row_count");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_count");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("valid_row_count");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_student_bulk_import_jobs_status");

                    b.ToTable("student_bulk_import_jobs", "student");
                });

            modelBuilder.Entity("UMS.Modules.Student.Domain.BulkImport.StudentBulkImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("ResultStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_student_id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "RowNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_student_bulk_import_rows_job_row_number");

                    b.HasIndex("JobId", "Status")
                        .HasDatabaseName("ix_student_bulk_import_rows_job_status");

                    b.ToTable("student_bulk_import_rows", "student");
                });

            modelBuilder.Entity("UMS.Modules.Student.Domain.StudentRequests.StudentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at");

                    b.Property<Guid?>("GeneratedDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_document_id");

                    b.Property<bool>("IsAgainstOwnDepartmentHead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_against_own_department_head");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<Guid?>("ReviewScopeNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_scope_node_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReviewScopeNodeId")
                        .HasDatabaseName("ix_student_requests_review_scope_node_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_requests_student_id");

                    b.HasIndex("StudentId", "RequestType")
                        .IsUnique()
                        .HasDatabaseName("ux_student_requests_student_id_request_type_open")
                        .HasFilter("status IN ('Submitted', 'UnderReview')");

                    b.ToTable("student_requests", "student");
                });

            modelBuilder.Entity("UMS.Modules.Student.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<Guid?>("IdCardDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_card_document_id");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("Mobile")
                        .HasColumnType("citext")
                        .HasColumnName("mobile");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<Guid>("OriginatingApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("originating_application_id");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_students_department_id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_students_identity_user_id")
                        .HasFilter("\"identity_user_id\" IS NOT NULL");

                    b.HasIndex("OriginatingApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ux_students_originating_application_id");

                    b.ToTable("students", "student");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "student");
                });

            modelBuilder.Entity("UMS.Modules.Student.Domain.Students.Student", b =>
                {
                    b.OwnsMany("UMS.Modules.Student.Domain.Guardians.Guardian", "Guardians", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContactEmail")
                                .HasColumnType("text")
                                .HasColumnName("contact_email");

                            b1.Property<string>("ContactPhone")
                                .HasColumnType("text")
                                .HasColumnName("contact_phone");

                            b1.Property<DateTimeOffset>("LinkedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("linked_at");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("relationship");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid")
                                .HasColumnName("student_id");

                            b1.HasKey("Id");

                            b1.HasIndex("StudentId")
                                .HasDatabaseName("ix_guardians_student_id");

                            b1.ToTable("guardians", "student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsMany("UMS.Modules.Student.Domain.Guardians.GuardianAccessGrant", "GuardianAccessGrants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("category");

                            b1.Property<DateTimeOffset>("GrantedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("granted_at");

                            b1.Property<Guid>("GuardianId")
                                .HasColumnType("uuid")
                                .HasColumnName("guardian_id");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid")
                                .HasColumnName("student_id");

                            b1.HasKey("Id");

                            b1.HasIndex("StudentId", "GuardianId")
                                .HasDatabaseName("ix_guardian_access_grants_student_guardian");

                            b1.ToTable("guardian_access_grants", "student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("UMS.Modules.Student.Domain.Students.StudentNumber", "StudentNumber", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AdmissionYear")
                                .HasColumnType("integer")
                                .HasColumnName("admission_year");

                            b1.Property<string>("FacultyCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("faculty_code");

                            b1.Property<long>("Sequence")
                                .HasColumnType("bigint")
                                .HasColumnName("student_number_sequence");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("student_number");

                            b1.HasKey("StudentId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ux_students_student_number");

                            b1.ToTable("students", "student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsMany("UMS.Modules.Student.Domain.Students.StudentStatusHistoryEntry", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ChangedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at");

                            b1.Property<Guid?>("ChangedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("changed_by_user_id");

                            b1.Property<string>("FromStatus")
                                .HasColumnType("text")
                                .HasColumnName("from_status");

                            b1.Property<string>("Reason")
                                .HasColumnType("text")
                                .HasColumnName("reason");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid")
                                .HasColumnName("student_id");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("to_status");

                            b1.HasKey("Id");

                            b1.HasIndex("StudentId")
                                .HasDatabaseName("ix_student_status_history_student_id");

                            b1.ToTable("student_status_history", "student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("UMS.Shared.Domain.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("family_name");

                            b1.Property<string>("FamilyNameBn")
                                .HasColumnType("text")
                                .HasColumnName("family_name_bn");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("given_name");

                            b1.Property<string>("GivenNameBn")
                                .HasColumnType("text")
                                .HasColumnName("given_name_bn");

                            b1.HasKey("StudentId");

                            b1.ToTable("students", "student");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("GuardianAccessGrants");

                    b.Navigation("Guardians");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("StatusHistory");

                    b.Navigation("StudentNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
