using System.Data;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using UMS.Modules.Audit.Application.Retention;
using UMS.Modules.Audit.Infrastructure.Persistence;

namespace UMS.Modules.Audit.Infrastructure.Retention;

/// <summary>
/// The real, Postgres-specific <see cref="IPartitionInspector"/> - reads partition metadata from
/// <c>pg_catalog</c> directly (there is no portable EF Core API for declarative partitioning) and
/// performs the actual archival DDL (design-decisions.md, "Archival/Retention Job Design").
/// </summary>
internal sealed partial class PostgresPartitionInspector(AuditDbContext context) : IPartitionInspector
{
    public async Task<IReadOnlyList<PartitionInfo>> ListPartitionsAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
            SELECT child.relname, pg_get_expr(child.relpartbound, child.oid)
            FROM pg_inherits
            JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
            JOIN pg_class child ON pg_inherits.inhrelid = child.oid
            JOIN pg_namespace ns ON ns.oid = parent.relnamespace
            WHERE ns.nspname = 'audit' AND parent.relname = 'audit_log_entries';
            """;

        var results = new List<PartitionInfo>();
        var wasOpenedHere = await EnsureConnectionOpenAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var connection = context.Database.GetDbConnection();
            await using var command = connection.CreateCommand();
            command.CommandText = sql;
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                var name = reader.GetString(0);
                var boundExpression = reader.GetString(1);
                if (TryParseBounds(boundExpression, out var start, out var end))
                {
                    results.Add(new PartitionInfo(name, start, end));
                }
            }
        }
        finally
        {
            if (wasOpenedHere)
            {
                await context.Database.CloseConnectionAsync().ConfigureAwait(false);
            }
        }

        return results;
    }

    public async Task<IReadOnlyList<string>> GetDistinctEntityTypesAsync(string partitionName, CancellationToken cancellationToken = default)
    {
        EnsureValidPartitionName(partitionName);

        var entityTypes = new List<string>();
        var wasOpenedHere = await EnsureConnectionOpenAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var connection = context.Database.GetDbConnection();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT DISTINCT entity_type FROM audit.{partitionName};";
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                entityTypes.Add(reader.GetString(0));
            }
        }
        finally
        {
            if (wasOpenedHere)
            {
                await context.Database.CloseConnectionAsync().ConfigureAwait(false);
            }
        }

        return entityTypes;
    }

    public async Task DetachPartitionAsync(string partitionName, CancellationToken cancellationToken = default)
    {
        EnsureValidPartitionName(partitionName);

        // Plain (non-CONCURRENTLY) detach: CONCURRENTLY requires running outside any transaction
        // block, which this method's caller (a scheduled maintenance job, per design-decisions.md)
        // is expected to run standalone rather than inside a wrapping transaction anyway, but a
        // plain detach is the simpler, always-valid v1 choice regardless of the caller's own
        // transactional context - a brief lock during a low-traffic maintenance window (edge-cases.md's
        // own accepted trade-off) rather than the tighter operational precondition CONCURRENTLY imposes.
        var sql = $"ALTER TABLE audit.audit_log_entries DETACH PARTITION audit.{partitionName};";
        await context.Database.ExecuteSqlRawAsync(sql, cancellationToken).ConfigureAwait(false);
    }

    // Guards every partition name this class ever interpolates into raw SQL - names only ever
    // come from this class's own ListPartitionsAsync (in turn generated by
    // Partitioning.PartitionNaming's fixed "audit_log_entries_yYYYYmMM" scheme), never external
    // input, but validating the shape here is a cheap, explicit defense-in-depth check against
    // SQL injection rather than trusting that invariant silently.
    [GeneratedRegex(@"^audit_log_entries_y\d{4}m\d{2}$")]
    private static partial Regex PartitionNamePattern();

    [GeneratedRegex(@"FROM\s*\('(?<from>[^']+)'\)\s*TO\s*\('(?<to>[^']+)'\)")]
    private static partial Regex BoundExpressionPattern();

    private static void EnsureValidPartitionName(string partitionName)
    {
        if (!PartitionNamePattern().IsMatch(partitionName))
        {
            throw new ArgumentException($"'{partitionName}' is not a recognized audit partition name.", nameof(partitionName));
        }
    }

    private static bool TryParseBounds(string boundExpression, out DateTimeOffset rangeStart, out DateTimeOffset rangeEndExclusive)
    {
        // pg_get_expr renders e.g. "FOR VALUES FROM ('2026-08-01 00:00:00+00') TO ('2026-09-01 00:00:00+00')".
        var match = BoundExpressionPattern().Match(boundExpression);
        if (match.Success
            && DateTimeOffset.TryParse(match.Groups["from"].Value, out rangeStart)
            && DateTimeOffset.TryParse(match.Groups["to"].Value, out rangeEndExclusive))
        {
            return true;
        }

        rangeStart = default;
        rangeEndExclusive = default;
        return false;
    }

    /// <summary>
    /// Opens the context's own connection through EF's own reference-counted open/close (rather
    /// than reaching for <see cref="System.Data.Common.DbConnection.OpenAsync()"/> directly),
    /// which is what makes it safe for this same <see cref="AuditDbContext"/> instance to keep
    /// being used normally by EF afterward. Returns whether this call is the one that opened it
    /// (and is therefore responsible for closing it again) - never closes a connection some other,
    /// still-in-progress caller opened.
    /// </summary>
    private async Task<bool> EnsureConnectionOpenAsync(CancellationToken cancellationToken)
    {
        if (context.Database.GetDbConnection().State == ConnectionState.Open)
        {
            return false;
        }

        await context.Database.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        return true;
    }
}
