using UMS.Modules.Identity.Domain.Common;
using UMS.Modules.Identity.Domain.Events;
using UMS.Modules.Identity.Domain.Users;

namespace UMS.Modules.Identity.Domain.Sessions;

/// <summary>
/// Backs one refresh token, independently revocable (glossary; requirement-spec.md identity §3).
/// One <see cref="Session"/> per login/device (design-decisions.md, "Token/Session Storage &amp;
/// Rotation Mechanism") - this is what lets "concurrent refresh from two devices" (edge-cases.md)
/// resolve naturally: each device's rotation chain lives in its own row, so one device's rotation
/// never interacts with another's.
/// </summary>
public sealed class Session : AggregateRoot<SessionId>
{
    private Session()
    {
    }

    private Session(
        SessionId id,
        UserId userId,
        string currentRefreshTokenHash,
        DateTimeOffset currentRefreshTokenExpiresAt,
        string? userAgent,
        string? createdFromIp,
        DateTimeOffset now)
    {
        Id = id;
        UserId = userId;
        CurrentRefreshTokenHash = currentRefreshTokenHash;
        CurrentRefreshTokenExpiresAt = currentRefreshTokenExpiresAt;
        UserAgent = userAgent;
        CreatedFromIp = createdFromIp;
        Status = SessionStatus.Active;
        CreatedAt = now;
        LastUsedAt = now;
    }

    public UserId UserId { get; private set; }

    public string CurrentRefreshTokenHash { get; private set; } = string.Empty;

    public DateTimeOffset CurrentRefreshTokenExpiresAt { get; private set; }

    public string? PreviousRefreshTokenHash { get; private set; }

    public DateTimeOffset? PreviousRefreshTokenConsumedAt { get; private set; }

    public string? UserAgent { get; private set; }

    public string? CreatedFromIp { get; private set; }

    public SessionStatus Status { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public DateTimeOffset LastUsedAt { get; private set; }

    public DateTimeOffset? RevokedAt { get; private set; }

    public string? RevokedReason { get; private set; }

    /// <summary>
    /// <paramref name="id"/> is generated by the caller (rather than internally) because the
    /// login application service needs a <see cref="SessionId"/> to embed in both the JWT access
    /// token and the refresh token's lookup prefix before this Session row can be built
    /// (design-decisions.md, "Token/Session Storage &amp; Rotation Mechanism").
    /// </summary>
    public static Session Open(
        SessionId id,
        UserId userId,
        string refreshTokenHash,
        DateTimeOffset refreshTokenExpiresAt,
        string? userAgent,
        string? createdFromIp,
        DateTimeOffset now)
    {
        var session = new Session(id, userId, refreshTokenHash, refreshTokenExpiresAt, userAgent, createdFromIp, now);
        session.Raise(new UserLoggedIn(userId, session.Id, now));
        return session;
    }

    /// <summary>
    /// Evaluates a presented refresh token against this Session's rotation state - the single
    /// place the "single-use rotation" invariant and its documented grace-window exception both
    /// live (requirement-spec.md identity §4; design-decisions.md, "Token/Session Storage &amp;
    /// Rotation Mechanism"; edge-cases.md, "Same-device concurrent refresh (two tabs)").
    /// </summary>
    public RefreshAttemptDecision EvaluateRefreshAttempt(string presentedTokenHash, DateTimeOffset now, TimeSpan graceWindow)
    {
        if (Status == SessionStatus.Revoked || now >= CurrentRefreshTokenExpiresAt)
        {
            return RefreshAttemptDecision.Rejected;
        }

        if (string.Equals(presentedTokenHash, CurrentRefreshTokenHash, StringComparison.Ordinal))
        {
            return RefreshAttemptDecision.RotateNormally;
        }

        if (PreviousRefreshTokenHash is not null
            && PreviousRefreshTokenConsumedAt is not null
            && string.Equals(presentedTokenHash, PreviousRefreshTokenHash, StringComparison.Ordinal)
            && now - PreviousRefreshTokenConsumedAt.Value <= graceWindow)
        {
            return RefreshAttemptDecision.GraceReuse;
        }

        return RefreshAttemptDecision.CompromiseDetected;
    }

    /// <summary>Rotates the refresh token - used for both the normal path and a grace-window reuse (both legitimately advance the chain).</summary>
    public void Rotate(string newRefreshTokenHash, DateTimeOffset newExpiresAt, DateTimeOffset now)
    {
        if (Status == SessionStatus.Revoked)
        {
            throw new InvalidOperationException("Cannot rotate a revoked Session.");
        }

        PreviousRefreshTokenHash = CurrentRefreshTokenHash;
        PreviousRefreshTokenConsumedAt = now;
        CurrentRefreshTokenHash = newRefreshTokenHash;
        CurrentRefreshTokenExpiresAt = newExpiresAt;
        LastUsedAt = now;
    }

    public void Revoke(string reason, DateTimeOffset now)
    {
        if (Status == SessionStatus.Revoked)
        {
            return;
        }

        Status = SessionStatus.Revoked;
        RevokedAt = now;
        RevokedReason = reason;
        Raise(new SessionRevoked(Id, UserId, reason, now));
    }
}
