// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Research.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Research.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20260908181140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Research.Domain.FundingBodies.FundingBody", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("funding_bodies", "research");
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.Grants.Grant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AwardDate")
                        .HasColumnType("date")
                        .HasColumnName("award_date");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FundingBodyId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_body_id");

                    b.Property<bool>("IsPubliclyVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_publicly_visible");

                    b.Property<DateTimeOffset?>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<bool>("RequiresPiReassignment")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_pi_reassignment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FundingAmount", "UMS.Modules.Research.Domain.Grants.Grant.FundingAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("funding_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("funding_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("FundingBodyId")
                        .HasDatabaseName("ix_grants_funding_body_id");

                    b.HasIndex("IsPubliclyVisible")
                        .HasDatabaseName("ix_grants_is_publicly_visible");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_grants_status");

                    b.ToTable("grants", "research");
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.InstitutionalRepositoryEntries.InstitutionalRepositoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DepositDate")
                        .HasColumnType("date")
                        .HasColumnName("deposit_date");

                    b.Property<Guid?>("SupervisingFacultyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervising_faculty_member_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("work_type");

                    b.HasKey("Id");

                    b.HasIndex("SupervisingFacultyMemberId")
                        .HasDatabaseName("ix_institutional_repository_entries_supervisor");

                    b.ToTable("institutional_repository_entries", "research");
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.Publications.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FundedByGrantIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("funded_by_grant_ids");

                    b.Property<bool>("IsPubliclyVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_publicly_visible");

                    b.Property<Guid?>("MergedIntoPublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_publication_id");

                    b.Property<string>("NormalizedDoi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_doi")
                        .HasComputedColumnSql("lower(btrim(doi))", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsPubliclyVisible")
                        .HasDatabaseName("ix_publications_is_publicly_visible");

                    b.HasIndex("MergedIntoPublicationId")
                        .HasDatabaseName("ix_publications_merged_into_publication_id");

                    b.HasIndex("NormalizedDoi")
                        .IsUnique()
                        .HasDatabaseName("ux_publications_normalized_doi")
                        .HasFilter("normalized_doi IS NOT NULL");

                    b.ToTable("publications", "research");
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.Publications.PublicationDuplicateCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidatePublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_publication_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("match_reason");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("publication_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId")
                        .HasDatabaseName("ix_publication_duplicate_candidates_publication_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_publication_duplicate_candidates_status");

                    b.ToTable("publication_duplicate_candidates", "research");
                });

            modelBuilder.Entity("UMS.Modules.Research.Infrastructure.Persistence.Inbox.ProcessedInboundEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "Source");

                    b.ToTable("processed_inbound_events", "research");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_outbox_messages_event_type");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "research");
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.Grants.Grant", b =>
                {
                    b.OwnsMany("UMS.Modules.Research.Domain.Grants.GrantInvestigator", "Investigators", b1 =>
                        {
                            b1.Property<Guid>("GrantId")
                                .HasColumnType("uuid")
                                .HasColumnName("grant_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<DateTimeOffset>("AddedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("added_at");

                            b1.Property<Guid>("FacultyMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("faculty_member_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("role");

                            b1.HasKey("GrantId", "Ordinal");

                            b1.HasIndex("GrantId", "FacultyMemberId")
                                .IsUnique()
                                .HasDatabaseName("ux_grant_investigators_grant_faculty_member");

                            b1.ToTable("grant_investigators", "research");

                            b1.WithOwner()
                                .HasForeignKey("GrantId");
                        });

                    b.OwnsOne("UMS.Shared.Domain.DateRange", "FundingPeriod", b1 =>
                        {
                            b1.Property<Guid>("GrantId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("funding_period_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("funding_period_start");

                            b1.HasKey("GrantId");

                            b1.ToTable("grants", "research");

                            b1.WithOwner()
                                .HasForeignKey("GrantId");
                        });

                    b.Navigation("FundingPeriod")
                        .IsRequired();

                    b.Navigation("Investigators");
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.InstitutionalRepositoryEntries.InstitutionalRepositoryEntry", b =>
                {
                    b.OwnsOne("UMS.Modules.Research.Domain.InstitutionalRepositoryEntries.Contributor", "Depositor", b1 =>
                        {
                            b1.Property<Guid>("InstitutionalRepositoryEntryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("FacultyMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("depositor_faculty_member_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("depositor_name");

                            b1.HasKey("InstitutionalRepositoryEntryId");

                            b1.ToTable("institutional_repository_entries", "research");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionalRepositoryEntryId");
                        });

                    b.OwnsOne("UMS.Modules.Research.Domain.InstitutionalRepositoryEntries.EmbargoPolicy", "Embargo", b1 =>
                        {
                            b1.Property<Guid>("InstitutionalRepositoryEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccessLevel")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("access_level");

                            b1.Property<DateOnly?>("EmbargoEndDate")
                                .HasColumnType("date")
                                .HasColumnName("embargo_end_date");

                            b1.Property<bool>("IsEmbargoed")
                                .HasColumnType("boolean")
                                .HasColumnName("is_embargoed");

                            b1.HasKey("InstitutionalRepositoryEntryId");

                            b1.HasIndex("IsEmbargoed", "EmbargoEndDate")
                                .HasDatabaseName("ix_institutional_repository_entries_embargo");

                            b1.ToTable("institutional_repository_entries", "research");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionalRepositoryEntryId");
                        });

                    b.Navigation("Depositor")
                        .IsRequired();

                    b.Navigation("Embargo")
                        .IsRequired();
                });

            modelBuilder.Entity("UMS.Modules.Research.Domain.Publications.Publication", b =>
                {
                    b.OwnsMany("UMS.Modules.Research.Domain.Publications.AuthorEntry", "Authors", b1 =>
                        {
                            b1.Property<Guid>("PublicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("publication_id");

                            b1.Property<int>("Ordinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordinal"));

                            b1.Property<string>("Affiliation")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("affiliation");

                            b1.Property<Guid?>("FacultyMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("faculty_member_id");

                            b1.Property<bool>("IsCorrespondingAuthor")
                                .HasColumnType("boolean")
                                .HasColumnName("is_corresponding_author");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("name");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("author_order");

                            b1.HasKey("PublicationId", "Ordinal");

                            b1.ToTable("publication_authors", "research");

                            b1.WithOwner()
                                .HasForeignKey("PublicationId");
                        });

                    b.OwnsOne("UMS.Modules.Research.Domain.Publications.CitationMetadata", "Citation", b1 =>
                        {
                            b1.Property<Guid>("PublicationId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CitationCount")
                                .HasColumnType("integer")
                                .HasColumnName("citation_count");

                            b1.Property<string>("Doi")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("doi");

                            b1.Property<DateOnly>("PublicationDate")
                                .HasColumnType("date")
                                .HasColumnName("publication_date");

                            b1.HasKey("PublicationId");

                            b1.ToTable("publications", "research");

                            b1.WithOwner()
                                .HasForeignKey("PublicationId");
                        });

                    b.OwnsOne("UMS.Modules.Research.Domain.Publications.Venue", "Venue", b1 =>
                        {
                            b1.Property<Guid>("PublicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("venue_name");

                            b1.Property<string>("Publisher")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("venue_publisher");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("venue_type");

                            b1.HasKey("PublicationId");

                            b1.ToTable("publications", "research");

                            b1.WithOwner()
                                .HasForeignKey("PublicationId");
                        });

                    b.Navigation("Authors");

                    b.Navigation("Citation")
                        .IsRequired();

                    b.Navigation("Venue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
