<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>UMS.Shared.Integrations</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UMS.Shared.ErrorHandling\UMS.Shared.ErrorHandling.csproj" />
  </ItemGroup>

</Project>
