<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>UMS.Modules.Reporting.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UMS.Modules.Reporting.Domain\UMS.Modules.Reporting.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.ErrorHandling\UMS.Shared.ErrorHandling.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Audit\UMS.Shared.Audit.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Domain\UMS.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Notifications\UMS.Shared.Notifications.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Documents\UMS.Shared.Documents.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Academic\UMS.Shared.Academic.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Admission\UMS.Shared.Admission.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Finance\UMS.Shared.Finance.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Faculty\UMS.Shared.Faculty.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Hostel\UMS.Shared.Hostel.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Library\UMS.Shared.Library.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Research\UMS.Shared.Research.csproj" />
    <ProjectReference Include="..\..\..\Shared\UMS.Shared.Content\UMS.Shared.Content.csproj" />
  </ItemGroup>

</Project>
