// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Reporting.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Reporting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Reporting.Domain.DashboardMetrics.DashboardMetric", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DataAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_as_of");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastRefreshAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refresh_attempted_at");

                    b.Property<string>("LastRefreshError")
                        .HasColumnType("text")
                        .HasColumnName("last_refresh_error");

                    b.Property<bool>("LastRefreshSucceeded")
                        .HasColumnType("boolean")
                        .HasColumnName("last_refresh_succeeded");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("dashboard_metrics", "reporting");
                });

            modelBuilder.Entity("UMS.Modules.Reporting.Domain.RegulatoryReports.RegulatoryReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters_json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SourceQueryReferencesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_query_references_json");

                    b.Property<string>("SupportedFormats")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("supported_formats");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_regulatory_report_definitions_name");

                    b.ToTable("regulatory_report_definitions", "reporting");
                });

            modelBuilder.Entity("UMS.Modules.Reporting.Domain.RegulatoryReports.RegulatoryReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("DefinitionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_snapshot_json");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.Property<string>("ParametersHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parameters_hash");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("ResultCsvContent")
                        .HasColumnType("text")
                        .HasColumnName("result_csv_content");

                    b.Property<Guid?>("ResultDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_document_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_regulatory_report_runs_status");

                    b.HasIndex("ParametersHash", "Status")
                        .HasDatabaseName("ix_regulatory_report_runs_parameters_hash_status");

                    b.ToTable("regulatory_report_runs", "reporting");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_outbox_messages_event_type");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "reporting");
                });

            modelBuilder.Entity("UMS.Modules.Reporting.Domain.RegulatoryReports.RegulatoryReportDefinition", b =>
                {
                    b.OwnsMany("UMS.Modules.Reporting.Domain.RegulatoryReports.ReportFieldSelection", "FieldSelections", b1 =>
                        {
                            b1.Property<int>("RowId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("row_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("RowId"));

                            b1.Property<Guid>("DefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("definition_id");

                            b1.Property<string>("FieldKey")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("field_key");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            b1.HasKey("RowId");

                            b1.HasIndex("DefinitionId")
                                .HasDatabaseName("ix_regulatory_report_definition_fields_definition_id");

                            b1.ToTable("regulatory_report_definition_fields", "reporting");

                            b1.WithOwner()
                                .HasForeignKey("DefinitionId");
                        });

                    b.Navigation("FieldSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
