// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMS.Modules.Academic.Infrastructure.Persistence;

#nullable disable

namespace UMS.Modules.Academic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AcademicDbContext))]
    partial class AcademicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("academic")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMS.Modules.Academic.Domain.AcademicSessions.AcademicSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("academic_sessions", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Attendance.AttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CorrectionWindowClose")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_window_close");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId", "SessionDate")
                        .IsUnique()
                        .HasDatabaseName("ux_attendance_sessions_courseoffering_date");

                    b.ToTable("attendance_sessions", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.CourseOfferings.CourseOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("integer")
                        .HasColumnName("enrolled_count");

                    b.Property<DateTimeOffset?>("InstructorAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instructor_assigned_at");

                    b.Property<Guid?>("InstructorFacultyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_faculty_member_id");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_course_offerings_semester_id");

                    b.ToTable("course_offerings", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_courses_code");

                    b.ToTable("courses", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Curricula.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurriculumVersion")
                        .HasColumnType("integer")
                        .HasColumnName("curriculum_version");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId", "CurriculumVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_curricula_program_version");

                    b.ToTable("curricula", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DropReason")
                        .HasColumnType("text")
                        .HasColumnName("drop_reason");

                    b.Property<DateTimeOffset?>("DroppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dropped_at");

                    b.Property<string>("PrerequisiteOverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("prerequisite_override_reason");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .HasDatabaseName("ix_enrollments_course_offering_id");

                    b.HasIndex("StudentId", "SemesterId")
                        .HasDatabaseName("ix_enrollments_student_semester");

                    b.HasIndex("StudentId", "CourseOfferingId", "SemesterId")
                        .IsUnique()
                        .HasDatabaseName("ux_enrollments_student_courseoffering_semester");

                    b.ToTable("enrollments", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Programs.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<int>("MaxCreditsPerSemester")
                        .HasColumnType("integer")
                        .HasColumnName("max_credits_per_semester");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresAdvisorApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_advisor_approval");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_programs_code");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_programs_department_id");

                    b.ToTable("programs", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.ResultPublications.ResultPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<int>("CorrectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("correction_count");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("locked_by_user_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .IsUnique()
                        .HasDatabaseName("ux_result_publications_course_offering_id");

                    b.ToTable("result_publications", "academic");
                });

            modelBuilder.Entity("UMS.Shared.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_outbox_messages_event_type");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "academic");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.AcademicSessions.AcademicSession", b =>
                {
                    b.OwnsMany("UMS.Modules.Academic.Domain.AcademicSessions.Semester", "Semesters", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AcademicSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("academic_session_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("Id");

                            b1.HasIndex("AcademicSessionId")
                                .HasDatabaseName("ix_semesters_academic_session_id");

                            b1.ToTable("semesters", "academic");

                            b1.WithOwner()
                                .HasForeignKey("AcademicSessionId");

                            b1.OwnsOne("UMS.Shared.Domain.DateRange", "DropWindow", b2 =>
                                {
                                    b2.Property<Guid>("SemesterId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateOnly>("End")
                                        .HasColumnType("date")
                                        .HasColumnName("drop_end");

                                    b2.Property<DateOnly>("Start")
                                        .HasColumnType("date")
                                        .HasColumnName("drop_start");

                                    b2.HasKey("SemesterId");

                                    b2.ToTable("semesters", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("SemesterId");
                                });

                            b1.OwnsOne("UMS.Shared.Domain.DateRange", "RegistrationWindow", b2 =>
                                {
                                    b2.Property<Guid>("SemesterId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateOnly>("End")
                                        .HasColumnType("date")
                                        .HasColumnName("registration_end");

                                    b2.Property<DateOnly>("Start")
                                        .HasColumnType("date")
                                        .HasColumnName("registration_start");

                                    b2.HasKey("SemesterId");

                                    b2.ToTable("semesters", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("SemesterId");
                                });

                            b1.Navigation("DropWindow")
                                .IsRequired();

                            b1.Navigation("RegistrationWindow")
                                .IsRequired();
                        });

                    b.OwnsOne("UMS.Shared.Domain.AcademicSessionCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("AcademicSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("code");

                            b1.HasKey("AcademicSessionId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ux_academic_sessions_code");

                            b1.ToTable("academic_sessions", "academic");

                            b1.WithOwner()
                                .HasForeignKey("AcademicSessionId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Attendance.AttendanceSession", b =>
                {
                    b.OwnsMany("UMS.Modules.Academic.Domain.Attendance.AttendanceRecord", "Records", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AttendanceSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("attendance_session_id");

                            b1.Property<Guid>("EnrollmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("enrollment_id");

                            b1.Property<DateTimeOffset>("MarkedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("marked_at");

                            b1.Property<Guid>("MarkedByFacultyMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("marked_by_faculty_member_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.HasKey("Id");

                            b1.HasIndex("AttendanceSessionId", "EnrollmentId")
                                .IsUnique()
                                .HasDatabaseName("ux_attendance_records_session_enrollment");

                            b1.ToTable("attendance_records", "academic");

                            b1.WithOwner()
                                .HasForeignKey("AttendanceSessionId");
                        });

                    b.Navigation("Records");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.CourseOfferings.CourseOffering", b =>
                {
                    b.OwnsMany("UMS.Modules.Academic.Domain.CourseOfferings.Exam", "Exams", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CourseOfferingId")
                                .HasColumnType("uuid")
                                .HasColumnName("course_offering_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseOfferingId")
                                .HasDatabaseName("ix_exams_course_offering_id");

                            b1.ToTable("exams", "academic");

                            b1.WithOwner()
                                .HasForeignKey("CourseOfferingId");

                            b1.OwnsMany("UMS.Modules.Academic.Domain.CourseOfferings.Assessment", "Assessments", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<Guid>("ExamId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("exam_id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.Property<decimal>("Weight")
                                        .HasColumnType("numeric(5,4)")
                                        .HasColumnName("weight");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExamId")
                                        .HasDatabaseName("ix_assessments_exam_id");

                                    b2.ToTable("assessments", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("ExamId");
                                });

                            b1.Navigation("Assessments");
                        });

                    b.OwnsMany("UMS.Modules.Academic.Domain.CourseOfferings.Section", "Sections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("code");

                            b1.Property<Guid>("CourseOfferingId")
                                .HasColumnType("uuid")
                                .HasColumnName("course_offering_id");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseOfferingId")
                                .HasDatabaseName("ix_sections_course_offering_id");

                            b1.ToTable("sections", "academic");

                            b1.WithOwner()
                                .HasForeignKey("CourseOfferingId");

                            b1.OwnsOne("UMS.Modules.Academic.Domain.Common.WeeklyTimeSlot", "Schedule", b2 =>
                                {
                                    b2.Property<Guid>("SectionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer")
                                        .HasColumnName("day_of_week");

                                    b2.Property<TimeOnly>("End")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("Start")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.HasKey("SectionId");

                                    b2.ToTable("sections", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("SectionId");
                                });

                            b1.Navigation("Schedule")
                                .IsRequired();
                        });

                    b.Navigation("Exams");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Courses.Course", b =>
                {
                    b.OwnsOne("UMS.Modules.Academic.Domain.Common.CreditHours", "CreditHours", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("credit_hours");

                            b1.HasKey("CourseId");

                            b1.ToTable("courses", "academic");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsMany("UMS.Modules.Academic.Domain.Courses.CoursePrerequisite", "Prerequisites", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid")
                                .HasColumnName("course_id");

                            b1.Property<Guid>("PrerequisiteCourseId")
                                .HasColumnType("uuid")
                                .HasColumnName("prerequisite_course_id");

                            b1.HasKey("CourseId", "PrerequisiteCourseId");

                            b1.ToTable("course_prerequisites", "academic");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("CreditHours")
                        .IsRequired();

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Curricula.Curriculum", b =>
                {
                    b.OwnsMany("UMS.Modules.Academic.Domain.Curricula.CurriculumCourseEntry", "Courses", b1 =>
                        {
                            b1.Property<Guid>("CurriculumId")
                                .HasColumnType("uuid")
                                .HasColumnName("curriculum_id");

                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid")
                                .HasColumnName("course_id");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("is_required");

                            b1.HasKey("CurriculumId", "CourseId");

                            b1.ToTable("curriculum_courses", "academic");

                            b1.WithOwner()
                                .HasForeignKey("CurriculumId");
                        });

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("UMS.Modules.Academic.Domain.Enrollments.Enrollment", b =>
                {
                    b.OwnsOne("UMS.Modules.Academic.Domain.Common.CreditHours", "CreditHoursAtEnrollment", b1 =>
                        {
                            b1.Property<Guid>("EnrollmentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("credit_hours_at_enrollment");

                            b1.HasKey("EnrollmentId");

                            b1.ToTable("enrollments", "academic");

                            b1.WithOwner()
                                .HasForeignKey("EnrollmentId");
                        });

                    b.OwnsOne("UMS.Modules.Academic.Domain.Enrollments.Grade", "Grade", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("EnrollmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("enrollment_id");

                            b1.Property<string>("LetterGrade")
                                .HasColumnType("text")
                                .HasColumnName("letter_grade");

                            b1.Property<DateTimeOffset?>("SubmittedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("submitted_at");

                            b1.Property<Guid?>("SubmittedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("submitted_by_user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("EnrollmentId")
                                .IsUnique()
                                .HasDatabaseName("ux_grades_enrollment_id");

                            b1.ToTable("grades", "academic");

                            b1.WithOwner()
                                .HasForeignKey("EnrollmentId");

                            b1.OwnsMany("UMS.Modules.Academic.Domain.Enrollments.AssessmentScoreEntry", "Scores", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<Guid>("AssessmentId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("assessment_id");

                                    b2.Property<Guid>("GradeId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("grade_id");

                                    b2.Property<decimal>("Score")
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("score");

                                    b2.HasKey("Id");

                                    b2.HasIndex("GradeId")
                                        .HasDatabaseName("ix_assessment_score_entries_grade_id");

                                    b2.ToTable("assessment_score_entries", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("GradeId");
                                });

                            b1.OwnsMany("UMS.Modules.Academic.Domain.Enrollments.GradeCorrectionEntry", "Corrections", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("CorrectedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("corrected_at");

                                    b2.Property<Guid>("CorrectedByUserId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("corrected_by_user_id");

                                    b2.Property<Guid>("GradeId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("grade_id");

                                    b2.Property<decimal>("NewScore")
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("new_score");

                                    b2.Property<decimal>("PreviousScore")
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("previous_score");

                                    b2.Property<string>("Reason")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("reason");

                                    b2.HasKey("Id");

                                    b2.HasIndex("GradeId")
                                        .HasDatabaseName("ix_grade_correction_entries_grade_id");

                                    b2.ToTable("grade_correction_entries", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("GradeId");
                                });

                            b1.OwnsOne("UMS.Shared.Domain.PercentageOrGpa", "CalculatedScore", b2 =>
                                {
                                    b2.Property<Guid>("GradeId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Scale")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("calculated_score_scale");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("calculated_score_value");

                                    b2.HasKey("GradeId");

                                    b2.ToTable("grades", "academic");

                                    b2.WithOwner()
                                        .HasForeignKey("GradeId");
                                });

                            b1.Navigation("CalculatedScore");

                            b1.Navigation("Corrections");

                            b1.Navigation("Scores");
                        });

                    b.Navigation("CreditHoursAtEnrollment")
                        .IsRequired();

                    b.Navigation("Grade");
                });
#pragma warning restore 612, 618
        }
    }
}
