<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UMS.Modules\Documents\UMS.Modules.Documents.Domain\UMS.Modules.Documents.Domain.csproj" />
    <ProjectReference Include="..\..\src\UMS.Modules\Documents\UMS.Modules.Documents.Application\UMS.Modules.Documents.Application.csproj" />
    <ProjectReference Include="..\..\src\UMS.Modules\Documents\UMS.Modules.Documents.Infrastructure\UMS.Modules.Documents.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Shared\UMS.Shared.ErrorHandling\UMS.Shared.ErrorHandling.csproj" />
    <ProjectReference Include="..\..\src\Shared\UMS.Shared.Audit\UMS.Shared.Audit.csproj" />
  </ItemGroup>

</Project>
